name: PR Check
on:
   pull_request:
    branches: [main]

jobs:
  my-job:
    name: PR check running
    runs-on: ubuntu-latest
   
    steps:
     - name: Print PR branch
       run: echo "PR check running for branch: $GITHUB_HEAD_REF"
